apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  namespace: soccerstats-production
  labels:
    app: customer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer-container
          image: gcr.io/sa-1s2022/customer-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: soccerstats-production
spec:
  selector:
    app: customer
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
