apiVersion: apps/v1
kind: Deployment
metadata:
  name: esb-deployment
  namespace: soccerstats-production
  labels:
    app: esb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: esb
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: esb
    spec:
      containers:
        - name: esb-container
          image: gcr.io/sa-1s2022/esb:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: esb-service
  namespace: soccerstats-production
spec:
  selector:
    app: esb
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 34.71.127.255
