apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-deployment
  namespace: soccerstats-production
  labels:
    app: match
spec:
  replicas: 2
  selector:
    matchLabels:
      app: match
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: match
    spec:
      containers:
        - name: match-container
          image: gcr.io/sa-1s2022/match-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: match-service
  namespace: soccerstats-production
spec:
  selector:
    app: match
  ports:
    - port: 5002
      targetPort: 5002
  type: ClusterIP
