apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-deployment
  namespace: soccerstats-production
  labels:
    app: team
spec:
  replicas: 2
  selector:
    matchLabels:
      app: team
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: team
    spec:
      containers:
        - name: team-container
          image: gcr.io/sa-1s2022/team-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: team-service
  namespace: soccerstats-production
spec:
  selector:
    app: team
  ports:
    - port: 5001
      targetPort: 5001
  type: ClusterIP
