apiVersion: apps/v1
kind: Deployment
metadata:
  name: administrator-deployment
  namespace: soccerstats-testing
  labels:
    app: administrator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: administrator
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: administrator
    spec:
      containers:
        - name: administrator-container
          image: gcr.io/sa-1s2022/administrator-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5011
          env:
            - name: DATABASE_DB
              value: SoccerStatsDevelop
---
apiVersion: v1
kind: Service
metadata:
  name: administrator-service
  namespace: soccerstats-testing
spec:
  selector:
    app: administrator
  ports:
    - port: 5011
      targetPort: 5011
  type: ClusterIP
