apiVersion: apps/v1
kind: Deployment
metadata:
  name: competition-deployment
  namespace: soccerstats-testing
  labels:
    app: competition
spec:
  replicas: 2
  selector:
    matchLabels:
      app: competition
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: competition
    spec:
      containers:
        - name: competition-container
          image: gcr.io/sa-1s2022/competition-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5003
          env:
            - name: DATABASE_DB
              value: SoccerStatsDevelop
---
apiVersion: v1
kind: Service
metadata:
  name: competition-service
  namespace: soccerstats-testing
spec:
  selector:
    app: competition
  ports:
    - port: 5003
      targetPort: 5003
  type: ClusterIP
