apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
  namespace: soccerstats-testing
  labels:
    app: post
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post-container
          image: gcr.io/sa-1s2022/post-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5007
          env:
            - name: DATABASE_DB
              value: SoccerStatsDevelop
---
apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: soccerstats-testing
spec:
  selector:
    app: post
  ports:
    - port: 5007
      targetPort: 5007
  type: ClusterIP
