apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-deployment
  namespace: soccerstats-testing
  labels:
    app: prediction
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prediction
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prediction
    spec:
      containers:
        - name: prediction-container
          image: gcr.io/sa-1s2022/prediction-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5011
          env:
            - name: DATABASE_DB
              value: SoccerStatsDevelop
---
apiVersion: v1
kind: Service
metadata:
  name: prediction-service
  namespace: soccerstats-testing
spec:
  selector:
    app: prediction
  ports:
    - port: 5009
      targetPort: 5009
  type: ClusterIP
