apiVersion: apps/v1
kind: Deployment
metadata:
  name: stadium-deployment
  namespace: soccerstats-testing
  labels:
    app: stadium
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stadium
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: stadium
    spec:
      containers:
        - name: stadium-container
          image: gcr.io/sa-1s2022/stadium-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5004
          env:
            - name: DATABASE_DB
              value: SoccerStatsDevelop
---
apiVersion: v1
kind: Service
metadata:
  name: stadium-service
  namespace: soccerstats-testing
spec:
  selector:
    app: stadium
  ports:
    - port: 5004
      targetPort: 5004
  type: ClusterIP
